spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/interviewPrep
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create-drop
  profiles:
    include: oauth

  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

jwt:
  secret: "12345678901234567890123456789010"